# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com

git:
  depth: 10

language: node_js

node_js:
  - 10

dist: trusty
sudo: false
